# -*- coding: utf-8 -*-
"""VideoSceneClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrpZ4w1YjSjc9jLi6NcMUnAoaxHtVfdU
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
files.upload()  # upload kaggle.json

import os
os.makedirs('/root/.config/kaggle', exist_ok=True)
os.system('mv kaggle.json /root/.config/kaggle/kaggle.json')
os.system('chmod 600 /root/.config/kaggle/kaggle.json')

!pip install kaggle -q
print("✓ Kaggle ready!")

import os

base = '/content/drive/MyDrive/Dataset'
classes = ['sports', 'news', 'movies', 'violence']

print("Checking your folder structure...\n")
for cls in classes:
    path = os.path.join(base, cls)
    if os.path.exists(path):
        count = len(os.listdir(path))
        print(f"  ✓ {cls}/  —  {count} files found")
    else:
        print(f"  ✗ {cls}/  —  FOLDER NOT FOUND, please create it")

!pip install torch torchvision opencv-python-headless scikit-learn matplotlib seaborn -q
print("All libraries ready!")

import cv2, os

VIDEO_DIR = '/content/drive/MyDrive/Dataset'        # your videos live here
FRAME_DIR = '/content/drive/MyDrive/Dataset_Frames' # frames will go here
EVERY_N   = 10  # save 1 frame every 10 frames (~3 per second for 30fps video)

classes = ['sports', 'news', 'movies', 'violence']

def extract_frames(video_path, output_dir, every_n=10):
    os.makedirs(output_dir, exist_ok=True)
    cap = cv2.VideoCapture(video_path)
    count, saved = 0, 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if count % every_n == 0:
            cv2.imwrite(f"{output_dir}/frame_{saved:05d}.jpg", frame)
            saved += 1
        count += 1
    cap.release()
    return saved

total_frames = 0
for cls in classes:
    vid_folder   = os.path.join(VIDEO_DIR, cls)
    frame_folder = os.path.join(FRAME_DIR, cls)
    videos = [f for f in os.listdir(vid_folder) if f.endswith(('.mp4', '.avi', '.mkv', '.mov'))]

    print(f"\n[{cls}] — {len(videos)} videos found")
    for vid in videos:
        out_dir = os.path.join(frame_folder, vid[:-4])
        n = extract_frames(os.path.join(vid_folder, vid), out_dir, EVERY_N)
        print(f"  {vid}  →  {n} frames saved")
        total_frames += n

print(f"\n✓ Done! Total frames extracted: {total_frames}")
print(f"✓ Frames saved to: {FRAME_DIR}")

import os

FRAME_DIR = "/content/drive/MyDrive/Dataset_Frames"

print("Checking frame dataset...\n")

total_frames = 0

for cls in os.listdir(FRAME_DIR):
    cls_path = os.path.join(FRAME_DIR, cls)

    if not os.path.isdir(cls_path):
        continue

    cls_frames = 0

    for video_folder in os.listdir(cls_path):
        video_path = os.path.join(cls_path, video_folder)

        if os.path.isdir(video_path):
            count = len([
                f for f in os.listdir(video_path)
                if f.endswith(".jpg")
            ])
            cls_frames += count

    total_frames += cls_frames
    print(f"{cls}: {cls_frames} frames")

print("\nTOTAL FRAMES:", total_frames)

cp -r /content/drive/MyDrive/Dataset_Frames /content/

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

FRAME_DIR = '/content/Dataset_Frames'

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

full_dataset = datasets.ImageFolder(FRAME_DIR, transform=transform)

print("Classes detected:", full_dataset.classes)
print("Total frames   :", len(full_dataset))

# 80% train, 20% validation
train_size = int(0.8 * len(full_dataset))
val_size   = len(full_dataset) - train_size
train_ds, val_ds = random_split(full_dataset, [train_size, val_size])

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  num_workers=0)
val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, num_workers=0)

print(f"\nTrain samples : {train_size}")
print(f"Val samples   : {val_size}")
print("DataLoaders ready!")

import torch.nn as nn
from torchvision import models

NUM_CLASSES = 4
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)  # should say 'cuda' if GPU is on

model = models.googlenet(pretrained=True, aux_logits=True)

# Freeze all pretrained layers
for param in model.parameters():
    param.requires_grad = False

# Replace the 3 output heads with 4-class versions
model.fc      = nn.Linear(1024, NUM_CLASSES)
model.aux1.fc2 = nn.Linear(1024, NUM_CLASSES)
model.aux2.fc2 = nn.Linear(1024, NUM_CLASSES)

# Unfreeze only the new heads
for head in [model.fc, model.aux1.fc2, model.aux2.fc2]:
    for param in head.parameters():
        param.requires_grad = True

model = model.to(device)
print("GoogLeNet loaded and ready!")

import torch
import torch.nn as nn
import torch.optim as optim

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=1e-3
)

scheduler = optim.lr_scheduler.StepLR(
    optimizer,
    step_size=5,
    gamma=0.5
)

# ---------------------------
# TRAIN
# ---------------------------
def train_epoch(model, loader):
    model.train()

    total_loss = 0.0
    correct = 0
    total = 0

    for imgs, labels in loader:
        imgs = imgs.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        out = model(imgs)
        logits = out.logits if hasattr(out, "logits") else out

        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        preds = logits.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return total_loss / len(loader), correct / total


# ---------------------------
# EVALUATE
# ---------------------------
def evaluate(model, loader):
    model.eval()

    correct = 0
    total = 0

    with torch.no_grad():
        for imgs, labels in loader:
            imgs = imgs.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            out = model(imgs)
            logits = out.logits if hasattr(out, "logits") else out

            preds = logits.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

    return correct / total


# ---------------------------
# TRAIN LOOP
# ---------------------------
EPOCHS = 10

print(f"{'Epoch':>6} | {'Loss':>8} | {'Train Acc':>10} | {'Val Acc':>8}")
print("-" * 45)

for epoch in range(EPOCHS):
    print(f"\n▶ Epoch {epoch+1} starting...")

    loss, train_acc = train_epoch(model, train_loader)
    val_acc = evaluate(model, val_loader)

    scheduler.step()

    print(f"{epoch+1:>6} | {loss:>8.4f} | {train_acc:>10.3f} | {val_acc:>8.3f}")


# ---------------------------
# SAVE MODEL (safe for Colab)
# ---------------------------
save_path = '/content/drive/MyDrive/scene_model.pth'
torch.save(model.state_dict(), save_path)
print(f"\n✓ Model saved locally at {save_path}")

import time

start = time.time()
imgs, labels = next(iter(train_loader))
end = time.time()

print("Batch load time:", end - start)

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

all_preds, all_labels = [], []
model.eval()
with torch.no_grad():
    for imgs, labels in val_loader:
        imgs   = imgs.to(device)
        out    = model(imgs)
        logits = out.logits if hasattr(out, 'logits') else out
        all_preds.extend(logits.argmax(1).cpu().numpy())
        all_labels.extend(labels.numpy())

class_names = full_dataset.classes

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title("Confusion Matrix — Scene Classifier")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/confusion_matrix.png', dpi=150)
plt.show()

print("\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=class_names))

import cv2
from PIL import Image
from collections import Counter

def predict_video(video_path, model, transform, class_names, every_n=10):
    cap = cv2.VideoCapture(video_path)
    predictions, count = [], 0
    model.eval()
    while True:
        ret, frame = cap.read()
        if not ret: break
        if count % every_n == 0:
            img    = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            tensor = transform(img).unsqueeze(0).to(device)
            with torch.no_grad():
                out    = model(tensor)
                logits = out.logits if hasattr(out, 'logits') else out
                predictions.append(class_names[logits.argmax(1).item()])
        count += 1
    cap.release()

    most_common = Counter(predictions).most_common(1)[0]
    print(f"\nVideo: {video_path}")
    print(f"Scene: {most_common[0].upper()}  ({most_common[1]}/{len(predictions)} frames agree)")
    print("\nFrame-by-frame breakdown:")
    for cls, cnt in Counter(predictions).most_common():
        bar = '█' * int(cnt / len(predictions) * 30)
        print(f"  {cls:<10} {bar} {cnt}")

# Change this path to your test video
predict_video('/content/drive/MyDrive/news_00001.mp4', model, transform, class_names)