# -*- coding: utf-8 -*-
"""notebook70db3e3343

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/nanshiyadav/notebook70db3e3343.221e6439-901d-4ce3-8ecf-05b4851fde67.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260514/auto/storage/goog4_request%26X-Goog-Date%3D20260514T101933Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D0f0a9922a15f4f7d4ca999d3e1cd9663aacce261a5d8eb9a7bc8afa1a0b8b9a211340d09d3c2087c5ca1918900211145470a1015f214e3420e291cd0be037ca77255f44b79c038d1a2dc4830f3385d5dd4e10f061f2f1e4747be2bc24fe7d8628e1c0e793bb54da6f661f5843c29626979eef15bf5a6c984593639e3c53e3834b3ce84f9e0429514684b0e79f382fd07ede57ada8ce5ed226721fd32939516c298b8bf624614721f5e352a5c1fdda56b3778fff1b9cd95c2c1cebded92fa3f7f4b7f117558a3e096386aecd1f6ceb5d717b7b995b7637d8a606a4a02bfdf9804a65dc03e03ede1b8a967d7238db7123e0d93934350b6317edd417c88aa5454e8
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
mohamedmustafa_real_life_violence_situations_dataset_path = kagglehub.dataset_download('mohamedmustafa/real-life-violence-situations-dataset')
abdallahwagih_ucf101_videos_path = kagglehub.dataset_download('abdallahwagih/ucf101-videos')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import os
import shutil
import kagglehub

# STEP 1: Datasets Download/Re-verify
# Ye variables image_a22002.png ke setup ko restore karenge
print("Downloading/Verifying datasets...")
mohamedmustafa_path = kagglehub.dataset_download('mohamedmustafa/real-life-violence-situations-dataset')
abdallahwagih_path = kagglehub.dataset_download('abdallahwagih/ucf101-videos')
celeb_df_path = kagglehub.dataset_download('reubensuju/celeb-df-v2')

# STEP 2: Create Folder Structure in Working Directory
base_path = '/kaggle/working/dataset'
classes = ['news', 'sports', 'movies', 'violence']

for cls in classes:
    os.makedirs(os.path.join(base_path, cls), exist_ok=True)

print("Folders created in /kaggle/working/dataset")

# STEP 3: Copy Data to Respective Folders (50 clips each for testing)

# --- Violence ---
source_v = os.path.join(mohamedmustafa_path, "Real Life Violence Dataset/Violence")
if os.path.exists(source_v):
    v_files = os.listdir(source_v)[:50]
    for f in v_files:
        shutil.copy(os.path.join(source_v, f), os.path.join(base_path, 'violence'))
    print(f"✅ Copied {len(v_files)} Violence videos.")

# --- News (Celeb-DF) ---
source_n = os.path.join(celeb_df_path, "Celeb-real")
if os.path.exists(source_n):
    n_files = os.listdir(source_n)[:50]
    for f in n_files:
        shutil.copy(os.path.join(source_n, f), os.path.join(base_path, 'news'))
    print(f"✅ Copied {len(n_files)} News videos.")

# --- Sports (UCF101 - Picking 'CricketShot' as example) ---
source_s = os.path.join(abdallahwagih_path, "UCF101/CricketShot")
if os.path.exists(source_s):
    s_files = os.listdir(source_s)[:50]
    for f in s_files:
        shutil.copy(os.path.join(source_s, f), os.path.join(base_path, 'sports'))
    print(f"✅ Copied {len(s_files)} Sports videos.")

# --- Movies (Temporary Fix: Using UCF101 'Punch' or 'TaiChi' as cinematic fillers) ---
# Jab tak real movies data nahi aata, ye folder khali na rahe isliye filler daal rahe hain
source_m = os.path.join(abdallahwagih_path, "UCF101/Punch")
if os.path.exists(source_m):
    m_files = os.listdir(source_m)[:50]
    for f in m_files:
        shutil.copy(os.path.join(source_m, f), os.path.join(base_path, 'movies'))
    print(f"✅ Copied {len(m_files)} Movie-filler videos.")

print("\n--- Final Dataset Summary ---")
for cls in classes:
    count = len(os.listdir(os.path.join(base_path, cls)))
    print(f"Folder '{cls}': {count} videos")

import os
import shutil

# 1. Path for the new Movie dataset
# Note: Kaggle folder names usually replace spaces with dashes
source_movies = "/kaggle/input/movie-identification-dataset-800-movies"
dest_movies = "/kaggle/working/dataset/movies"

# Ensure the destination is clean (removing the temporary filler if it existed)
if os.path.exists(dest_movies):
    shutil.rmtree(dest_movies)
os.makedirs(dest_movies, exist_ok=True)

if os.path.exists(source_movies):
    # This dataset likely has many subfolders. We'll grab clips from the first few.
    movie_folders = [f for f in os.listdir(source_movies) if os.path.isdir(os.path.join(source_movies, f))]

    count = 0
    for folder in movie_folders:
        folder_path = os.path.join(source_movies, folder)
        files = os.listdir(folder_path)
        for f in files:
            if count >= 50: break # Keep it balanced with 50 per category for now
            shutil.copy(os.path.join(folder_path, f), dest_movies)
            count += 1
        if count >= 50: break

    print(f"✅ Successfully updated 'movies' folder with {count} real movie clips.")
else:
    print("Movie dataset path not found. Please check the 'Input' sidebar for the exact folder name.")

import os
import shutil
import kagglehub

# --- STEP 1: INITIALIZE WORKING DIRECTORY ---
base_path = '/kaggle/working/dataset'
classes = ['news', 'sports', 'movies', 'violence']

# Reset the working directory to ensure a clean start
if os.path.exists(base_path):
    shutil.rmtree(base_path)

for cls in classes:
    os.makedirs(os.path.join(base_path, cls), exist_ok=True)

print("🚀 Starting Dataset Consolidation...")

# --- STEP 2: DEFINE PATHS (Auto-Detect Logic) ---
# We look into /kaggle/input to find the correct folder names automatically
input_folders = os.listdir("/kaggle/input")

def find_path(keyword):
    for folder in input_folders:
        if keyword.lower() in folder.lower():
            return os.path.join("/kaggle/input", folder)
    return None

path_violence_raw = find_path('violence')
path_ucf101_raw = find_path('ucf101')
path_celeb_raw = find_path('celeb')
path_movies_raw = find_path('movie-identification')

# --- STEP 3: HELPER FUNCTION TO COPY VIDEOS ---
def collect_videos(source_root, dest_class, limit=50):
    dest_dir = os.path.join(base_path, dest_class)
    found_files = []
    # Recursively find all video files
    for root, dirs, files in os.walk(source_root):
        for file in files:
            if file.lower().endswith(('.mp4', '.avi', '.mkv', '.mov')):
                found_files.append(os.path.join(root, file))

    # Copy limited number of files
    count = 0
    for file_path in found_files[:limit]:
        shutil.copy(file_path, dest_dir)
        count += 1
    return count

# --- STEP 4: EXECUTE COLLECTION ---

# 1. Violence
if path_violence_raw:
    # Specific subfolder check for the known dataset structure
    v_sub = os.path.join(path_violence_raw, "Real Life Violence Dataset/Violence")
    actual_v_source = v_sub if os.path.exists(v_sub) else path_violence_raw
    c = collect_videos(actual_v_source, 'violence')
    print(f"✅ Violence: Copied {c} videos.")
else:
    print("❌ Violence dataset not found in Input.")

# 2. News (Celeb-DF)
if path_celeb_raw:
    c = collect_videos(path_celeb_raw, 'news')
    print(f"✅ News (Celeb-DF): Copied {c} videos.")
else:
    print("❌ Celeb-DF (News) dataset not found in Input.")

# 3. Sports (UCF101)
if path_ucf101_raw:
    # Looking for a specific sport like Cricket or Football within UCF101
    s_sub = os.path.join(path_ucf101_raw, "UCF101/CricketShot")
    actual_s_source = s_sub if os.path.exists(s_sub) else path_ucf101_raw
    c = collect_videos(actual_s_source, 'sports')
    print(f"✅ Sports (UCF101): Copied {c} videos.")
else:
    print("❌ UCF101 (Sports) dataset not found in Input.")

# 4. Movies
if path_movies_raw:
    c = collect_videos(path_movies_raw, 'movies')
    print(f"✅ Movies: Copied {c} videos.")
else:
    print("❌ Movie Identification dataset not found in Input.")

# --- STEP 5: FINAL VERIFICATION ---
print("\n--- Final Dataset Summary (/kaggle/working/dataset) ---")
for cls in classes:
    count = len(os.listdir(os.path.join(base_path, cls)))
    status = "READY" if count > 0 else "EMPTY ⚠️"
    print(f"Class: {cls.ljust(10)} | Count: {count} | Status: {status}")

import os
print(os.listdir("/kaggle/input"))

import os
import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms

# 1. Configuration
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BASE_PATH = '/kaggle/working/dataset'
CLASSES = ['news', 'sports', 'violence'] # Movies removed
IMG_SIZE = 224
SEQ_LEN = 20  # Ek video se kitni frames leni hain
BATCH_SIZE = 4
EPOCHS = 10

# 2. Video Dataset Class
class VideoDataset(Dataset):
    def __init__(self, base_dir, sequence_length=20):
        self.data = []
        self.labels = []
        self.seq_len = sequence_length

        for idx, cls in enumerate(CLASSES):
            cls_path = os.path.join(base_dir, cls)
            if not os.path.exists(cls_path): continue
            for video_name in os.listdir(cls_path):
                self.data.append(os.path.join(cls_path, video_name))
                self.labels.append(idx)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        video_path = self.data[idx]
        cap = cv2.VideoCapture(video_path)
        frames = []

        while len(frames) < self.seq_len:
            ret, frame = cap.read()
            if not ret: break
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (IMG_SIZE, IMG_SIZE))
            frames.append(frame)
        cap.release()

        # Padding if video is too short
        while len(frames) < self.seq_len:
            frames.append(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))

        frames = np.array(frames)
        # Transform for GoogLeNet (Pre-trained)
        transform = transforms.Compose([
            transforms.ToPILImage(),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])

        transformed_frames = torch.stack([transform(f) for f in frames])
        return transformed_frames, self.labels[idx]

# 3. Model Architecture (GoogLeNet + LSTM)
class VideoClassifier(nn.Module):
    def __init__(self, num_classes):
        super(VideoClassifier, self).__init__()
        # Pre-trained GoogLeNet as Feature Extractor
        googlenet = models.googlenet(weights='DEFAULT')
        self.feature_extractor = nn.Sequential(*list(googlenet.children())[:-2])
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))

        # LSTM for Sequence Processing
        self.lstm = nn.LSTM(input_size=1024, hidden_size=256, num_layers=1, batch_first=True)
        self.fc = nn.Linear(256, num_classes)

    def forward(self, x):
        batch_size, seq_len, c, h, w = x.shape
        # Extract features for each frame
        ii = x.view(batch_size * seq_len, c, h, w)
        features = self.feature_extractor(ii)
        features = self.avgpool(features)
        features = features.view(batch_size, seq_len, -1)

        # Pass through LSTM
        lstm_out, _ = self.lstm(features)
        final_out = self.fc(lstm_out[:, -1, :]) # Take the last hidden state
        return final_out

# 4. Training Execution
print(f"Using Device: {DEVICE}")
dataset = VideoDataset(BASE_PATH)
train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

model = VideoClassifier(num_classes=len(CLASSES)).to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

print("Starting Training...")
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for videos, labels in train_loader:
        videos, labels = videos.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        outputs = model(videos)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch [{epoch+1}/{EPOCHS}], Loss: {total_loss/len(train_loader):.4f}")

print("Training Complete! Aapka project 3 classes ke liye ready hai.")

import os
base_dir = '/kaggle/working/dataset'
for cls in ['news', 'sports', 'violence']:
    path = os.path.join(base_dir, cls)
    if os.path.exists(path):
        print(f"Folder {cls}: {len(os.listdir(path))} files found.")
    else:
        print(f"Folder {cls} does NOT exist!")

import os
import shutil
import kagglehub

# 1. Setup paths
base_path = '/kaggle/working/dataset'
classes = ['news', 'sports', 'violence']

if os.path.exists(base_path):
    shutil.rmtree(base_path)

for cls in classes:
    os.makedirs(os.path.join(base_path, cls), exist_ok=True)

# 2. Download/Locate Datasets
print("Locating datasets...")
v_path = kagglehub.dataset_download('mohamedmustafa/real-life-violence-situations-dataset')
s_path = kagglehub.dataset_download('abdallahwagih/ucf101-videos')
n_path = kagglehub.dataset_download('reubensuju/celeb-df-v2')

# 3. Copy Function
def quick_copy(src, dest_cls):
    count = 0
    for root, dirs, files in os.walk(src):
        for f in files:
            if count >= 50: break
            if f.lower().endswith(('.mp4', '.avi')):
                shutil.copy(os.path.join(root, f), os.path.join(base_path, dest_cls))
                count += 1
    print(f"✅ {dest_cls.upper()}: Copied {count} videos.")

# Execute Copy
quick_copy(os.path.join(v_path, "Real Life Violence Dataset/Violence"), 'violence')
quick_copy(os.path.join(s_path, "UCF101/CricketShot"), 'sports')
quick_copy(os.path.join(n_path, "Celeb-real"), 'news')

print("\nFolders are now READY. Ab aap training wala code run kar sakti hain.")

import os
import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms

# 1. Configuration
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BASE_PATH = '/kaggle/working/dataset'
CLASSES = ['news', 'sports', 'violence'] # Movies removed
IMG_SIZE = 224
SEQ_LEN = 20  # Ek video se kitni frames leni hain
BATCH_SIZE = 4
EPOCHS = 10

# 2. Video Dataset Class
class VideoDataset(Dataset):
    def __init__(self, base_dir, sequence_length=20):
        self.data = []
        self.labels = []
        self.seq_len = sequence_length

        for idx, cls in enumerate(CLASSES):
            cls_path = os.path.join(base_dir, cls)
            if not os.path.exists(cls_path): continue
            for video_name in os.listdir(cls_path):
                self.data.append(os.path.join(cls_path, video_name))
                self.labels.append(idx)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        video_path = self.data[idx]
        cap = cv2.VideoCapture(video_path)
        frames = []

        while len(frames) < self.seq_len:
            ret, frame = cap.read()
            if not ret: break
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (IMG_SIZE, IMG_SIZE))
            frames.append(frame)
        cap.release()

        # Padding if video is too short
        while len(frames) < self.seq_len:
            frames.append(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))

        frames = np.array(frames)
        # Transform for GoogLeNet (Pre-trained)
        transform = transforms.Compose([
            transforms.ToPILImage(),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])

        # transformed_frames = torch.stack([transform(f) for f in frames])
        # Is part ko __getitem__ mein replace kar sakti hain safety ke liye
        try:
          transformed_frames = torch.stack([transform(f) for f in frames])
        except Exception as e:
          # Agar kisi video mein error aaye toh zero tensor bhej do
          transformed_frames = torch.zeros((self.seq_len, 3, IMG_SIZE, IMG_SIZE))

        return transformed_frames, self.labels[idx]

# 3. Model Architecture (GoogLeNet + LSTM)
class VideoClassifier(nn.Module):
    def __init__(self, num_classes):
        super(VideoClassifier, self).__init__()
        # Pre-trained GoogLeNet as Feature Extractor
        googlenet = models.googlenet(weights='DEFAULT')
        self.feature_extractor = nn.Sequential(*list(googlenet.children())[:-2])
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))

        # LSTM for Sequence Processing
        self.lstm = nn.LSTM(input_size=1024, hidden_size=256, num_layers=1, batch_first=True)
        self.fc = nn.Linear(256, num_classes)

    def forward(self, x):
        batch_size, seq_len, c, h, w = x.shape
        # Extract features for each frame
        ii = x.view(batch_size * seq_len, c, h, w)
        features = self.feature_extractor(ii)
        features = self.avgpool(features)
        features = features.view(batch_size, seq_len, -1)

        # Pass through LSTM
        lstm_out, _ = self.lstm(features)
        final_out = self.fc(lstm_out[:, -1, :]) # Take the last hidden state
        return final_out

# 4. Training Execution
print(f"Using Device: {DEVICE}")
dataset = VideoDataset(BASE_PATH)
train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

model = VideoClassifier(num_classes=len(CLASSES)).to(DEVICE)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

print("Starting Training...")
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for videos, labels in train_loader:
        videos, labels = videos.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        outputs = model(videos)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch [{epoch+1}/{EPOCHS}], Loss: {total_loss/len(train_loader):.4f}")

print("Training Complete! Aapka project 3 classes ke liye ready hai.")

import os
import shutil
import kagglehub

base_path = '/kaggle/working/dataset'
classes = ['news', 'sports', 'violence']

if os.path.exists(base_path):
    shutil.rmtree(base_path)

for cls in classes:
    os.makedirs(os.path.join(base_path, cls), exist_ok=True)

print("Starting Data Restoration...")

try:
    v_path = kagglehub.dataset_download('mohamedmustafa/real-life-violence-situations-dataset')
    s_path = kagglehub.dataset_download('abdallahwagih/ucf101-videos')
    n_path = kagglehub.dataset_download('reubensuju/celeb-df-v2')

    def move_data(src_root, dest_cls):
        count = 0
        for root, dirs, files in os.walk(src_root):
            for f in files:
                if count >= 50: break
                if f.lower().endswith(('.mp4', '.avi')):
                    shutil.copy(os.path.join(root, f), os.path.join(base_path, dest_cls))
                    count += 1
        print(f" {dest_cls.upper()}: Moved {count} videos.")

    move_data(v_path, 'violence')
    move_data(s_path, 'sports')
    move_data(n_path, 'news')

    print("\n--- STATUS: READY TO TRAIN ---")
except Exception as e:
    print(f"Error locating datasets: {e}")
    print("Tip: Make sure these 3 datasets are added in the '+ Add Input' sidebar.")

import os
import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms

#Configuration
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BASE_PATH = '/kaggle/working/dataset'
CLASSES = ['news', 'sports', 'violence']
IMG_SIZE = 224
SEQ_LEN = 20
BATCH_SIZE = 4
EPOCHS = 10

#Updated Video Dataset Class (Recursive Search)
class VideoDataset(Dataset):
    def __init__(self, base_dir, sequence_length=20):
        self.data = []
        self.labels = []
        self.seq_len = sequence_length
        valid_exts = ('.mp4', '.avi', '.mkv', '.mov')

        for idx, cls in enumerate(CLASSES):
            cls_path = os.path.join(base_dir, cls)
            if not os.path.exists(cls_path):
                continue

            video_count = 0
            for root, dirs, files in os.walk(cls_path):
                for f in files:
                    if f.lower().endswith(valid_exts):
                        self.data.append(os.path.join(root, f))
                        self.labels.append(idx)
                        video_count += 1
            print(f"Loaded {video_count} videos for class: {cls}")

        if len(self.data) == 0:
            raise ValueError("Zero videos found! Please check if files were copied correctly.")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        try:
            video_path = self.data[idx]
            cap = cv2.VideoCapture(video_path)
            frames = []

            while len(frames) < self.seq_len:
                ret, frame = cap.read()
                if not ret: break
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                frame = cv2.resize(frame, (IMG_SIZE, IMG_SIZE))
                frames.append(frame)
            cap.release()

            while len(frames) < self.seq_len:
                frames.append(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))

            frames = np.array(frames)
            transform = transforms.Compose([
                transforms.ToPILImage(),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
            ])

            transformed_frames = torch.stack([transform(f) for f in frames])
            return transformed_frames, self.labels[idx]
        except Exception as e:
            return torch.zeros((self.seq_len, 3, IMG_SIZE, IMG_SIZE)), self.labels[idx]

class VideoClassifier(nn.Module):
    def __init__(self, num_classes):
        super(VideoClassifier, self).__init__()
        googlenet = models.googlenet(weights='DEFAULT')
        self.feature_extractor = nn.Sequential(*list(googlenet.children())[:-2])
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.lstm = nn.LSTM(input_size=1024, hidden_size=256, num_layers=1, batch_first=True)
        self.fc = nn.Linear(256, num_classes)

    def forward(self, x):
        batch_size, seq_len, c, h, w = x.shape
        ii = x.view(batch_size * seq_len, c, h, w)
        features = self.feature_extractor(ii)
        features = self.avgpool(features)
        features = features.view(batch_size, seq_len, -1)
        lstm_out, _ = self.lstm(features)
        return self.fc(lstm_out[:, -1, :])

print(f"Using Device: {DEVICE}")
try:
    dataset = VideoDataset(BASE_PATH)
    train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    model = VideoClassifier(num_classes=len(CLASSES)).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    print("Starting Training...")
    for epoch in range(EPOCHS):
        model.train()
        total_loss = 0
        for videos, labels in train_loader:
            videos, labels = videos.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(videos)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"Epoch [{epoch+1}/{EPOCHS}], Loss: {total_loss/len(train_loader):.4f}")
except Exception as e:
    print(f"Critical Error: {e}")

import torch
import random

def test_random_video(model, dataset):
    model.eval()

    idx = random.randint(0, len(dataset)-1)
    video_tensor, true_label = dataset[idx]
    video_path = dataset.data[idx]

    input_tensor = video_tensor.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        outputs = model(input_tensor)
        _, predicted = torch.max(outputs, 1)

    print(f"--- Video Testing ---")
    print(f"Video Path: {video_path}")
    print(f"True Label: {CLASSES[true_label]}")
    print(f"Predicted Label: {CLASSES[predicted.item()]}")

    if true_label == predicted.item():
        print("✅ Result: Correct Prediction!")
    else:
        print("❌ Result: Wrong Prediction.")

# Run the test
test_random_video(model, dataset)

def test_with_confidence(model, dataset):
    model.eval()
    idx = random.randint(0, len(dataset)-1)
    video_tensor, true_label = dataset[idx]

    input_tensor = video_tensor.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = torch.nn.functional.softmax(outputs, dim=1) # Get percentages
        conf, predicted = torch.max(probabilities, 1)

    print(f"Video: {dataset.data[idx]}")
    print(f"True: {CLASSES[true_label]} | Predicted: {CLASSES[predicted.item()]}")
    print(f"Confidence: {conf.item()*100:.2f}%")

    for i, cls in enumerate(CLASSES):
        print(f"-> {cls}: {probabilities[0][i].item()*100:.2f}%")

test_with_confidence(model, dataset)

SEQ_LEN = 30  # (more temporal context)
EPOCHS = 12   #  epochs stable for learning
LR = 0.0001   # Learning rate dec (for finer weight updates)

class EnhancedVideoClassifier(nn.Module):
    def __init__(self, num_classes):
        super(EnhancedVideoClassifier, self).__init__()
        googlenet = models.googlenet(weights='DEFAULT')
        self.feature_extractor = nn.Sequential(*list(googlenet.children())[:-2])
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))

        # LSTM with Dropout to prevent overfitting
        self.lstm = nn.LSTM(input_size=1024, hidden_size=512, num_layers=2,
                            batch_first=True, dropout=0.3)

        self.fc = nn.Sequential(
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        batch_size, seq_len, c, h, w = x.shape
        ii = x.view(batch_size * seq_len, c, h, w)
        features = self.feature_extractor(ii)
        features = self.avgpool(features)
        features = features.view(batch_size, seq_len, -1)

        lstm_out, _ = self.lstm(features)
        return self.fc(lstm_out[:, -1, :])

# Re-initializing for the second round
model = EnhancedVideoClassifier(num_classes=len(CLASSES)).to(DEVICE)
optimizer = optim.Adam(model.parameters(), lr=LR)
dataset = VideoDataset(BASE_PATH, sequence_length=SEQ_LEN) # Reload with new seq_len
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

print("🚀 Starting Refined Training...")
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for videos, labels in train_loader:
        videos, labels = videos.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(videos)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch [{epoch+1}/{EPOCHS}], Loss: {total_loss/len(train_loader):.4f}")

def test_final_model(model, dataset):
    model.eval()
    idx = random.randint(0, len(dataset)-1)
    video_tensor, true_label = dataset[idx]

    input_tensor = video_tensor.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = torch.nn.functional.softmax(outputs, dim=1)
        conf, predicted = torch.max(probabilities, 1)

    print(f"--- 🚀 Final Model Test ---")
    print(f"Video: {dataset.data[idx]}")
    print(f"True: {CLASSES[true_label].upper()} | Predicted: {CLASSES[predicted.item()].upper()}")
    print(f"Confidence Score: {conf.item()*100:.2f}%")

    print("\nProbability Distribution:")
    for i, cls in enumerate(CLASSES):
        print(f"  {cls.ljust(10)}: {probabilities[0][i].item()*100:.2f}%")

    if true_label == predicted.item():
        print("\n🎯 Result: ACCURATE")
    else:
        print("\n⚠️ Result: MISCLASSIFIED")

test_final_model(model, dataset)

# to save weights
torch.save(model.state_dict(), 'action_recognition_model.pth')
print("Model saved as action_recognition_model.pth")

# make empty architecture
model = EnhancedVideoClassifier(num_classes=3).to(DEVICE)

#saved weights
model.load_state_dict(torch.load('action_recognition_model.pth'))

#ready for prediction
model.eval()
print("Model reloaded successfully without training!")

from google.colab import drive
drive.mount('/content/drive')
# save directly in google drive
torch.save(model.state_dict(), '/content/drive/MyDrive/action_recognition_model.pth')