# -*- coding: utf-8 -*-
"""dl_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDwmX706OSEhGvtxQ32El4C9JY2gikpu
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("reubensuju/celeb-df-v2")

print("Path to dataset files:", path)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("pratt3000/moviesviolencenonviolence")

print("Path to dataset files:", path)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("abdallahwagih/ucf101-videos")

print("Path to dataset files:", path)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohamedmustafa/real-life-violence-situations-dataset")

print("Path to dataset files:", path)

import kagglehub
sports_path = kagglehub.dataset_download("abdallahwagih/ucf101-videos")
print("Sports dataset at:", sports_path)

# ------------------------------
# 1. Install dependencies
# ------------------------------
!pip install -q torch torchvision opencv-python scikit-learn tqdm

import os
import glob
import random
import shutil
import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from tqdm import tqdm

# ------------------------------
# 2. Dataset paths (from your download outputs)
# ------------------------------
DATASET_CONFIG = {
    "Sports": {
        "source": "/kaggle/input/ucf101-videos",
        "filter": None,   # take all videos
    },
    "News": {
        "source": "/root/.cache/kagglehub/datasets/reubensuju/celeb-df-v2/versions/1",
        "filter": None,
    },
    "Violence": {
        "source": "/root/.cache/kagglehub/datasets/mohamedmustafa/real-life-violence-situations-dataset/versions/1",
        "filter": lambda p: 'Violence' in p and 'NonViolence' not in p,
    },
    "Movies": {
        "source": "/root/.cache/kagglehub/datasets/pratt3000/moviesviolencenonviolence/versions/1",
        "filter": lambda p: 'NonViolence' in p,
    },
}

CLASS_NAMES = ["Sports", "News", "Movies", "Violence"]
BASE_DIR = "/content/balanced_dataset"

# ------------------------------
# 3. Helper: collect all video paths per class (with filtering)
# ------------------------------
def collect_videos(class_name, src_root, filter_func):
    if not os.path.exists(src_root):
        print(f"Warning: {src_root} not found for {class_name}")
        return []
    video_exts = ('*.mp4', '*.avi', '*.mov', '*.mkv', '*.webm')
    videos = []
    for ext in video_exts:
        for path in glob.glob(os.path.join(src_root, '**', ext), recursive=True):
            if filter_func is not None and not filter_func(path):
                continue
            videos.append(path)
    return videos

# Collect all videos per class
class_videos = {}
for class_name, info in DATASET_CONFIG.items():
    videos = collect_videos(class_name, info["source"], info["filter"])
    class_videos[class_name] = videos
    print(f"{class_name}: {len(videos)} videos found")

# Find the smallest class size (Movies has 123)
min_size = min(len(v) for v in class_videos.values())
print(f"\nBalancing: taking {min_size} videos from each class (total {min_size * len(CLASS_NAMES)} videos).")

# ------------------------------
# 4. Copy balanced subset to unified folder
# ------------------------------
for cls in CLASS_NAMES:
    os.makedirs(os.path.join(BASE_DIR, cls), exist_ok=True)

random.seed(42)
for class_name, video_list in class_videos.items():
    target_dir = os.path.join(BASE_DIR, class_name)
    selected = random.sample(video_list, min_size)   # downsample large classes
    for src in selected:
        shutil.copy(src, target_dir)
    print(f"Copied {len(selected)} videos to {class_name}")

# ------------------------------
# 5. Dataset class (extract 16 frames per video)
# ------------------------------
FRAMES_PER_VIDEO = 16
IMG_SIZE = 224
transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

class BalancedVideoDataset(Dataset):
    def __init__(self, root_dir, frames_per_video=FRAMES_PER_VIDEO, transform=None):
        self.root_dir = root_dir
        self.frames_per_video = frames_per_video
        self.transform = transform
        self.samples = []
        for class_name in CLASS_NAMES:
            class_path = os.path.join(root_dir, class_name)
            if not os.path.isdir(class_path):
                continue
            label = CLASS_NAMES.index(class_name)
            for ext in ('*.mp4', '*.avi', '*.mov', '*.mkv', '*.webm'):
                for video_path in glob.glob(os.path.join(class_path, ext)):
                    self.samples.append((video_path, label))
        print(f"Balanced dataset ready: {len(self.samples)} videos total.")

    def _extract_frames(self, video_path):
        cap = cv2.VideoCapture(video_path)
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            cap.release()
            raise ValueError("No frames")
        indices = np.linspace(0, total_frames - 1, self.frames_per_video, dtype=int)
        frames = []
        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()
            if not ret:
                frame = frames[-1] if frames else np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8)
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            if self.transform:
                frame = self.transform(frame)
            frames.append(frame)
        cap.release()
        return torch.stack(frames)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        video_path, label = self.samples[idx]
        try:
            frames = self._extract_frames(video_path)
        except Exception:
            frames = torch.randn(self.frames_per_video, 3, IMG_SIZE, IMG_SIZE)
        return frames, label

# ------------------------------
# 6. Model: GoogLeNet (frozen) + LSTM
# ------------------------------
NUM_CLASSES = 4
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class SceneClassifier(nn.Module):
    def __init__(self, hidden_size=256, num_layers=2):
        super().__init__()
        # GoogLeNet with pretrained weights (if internet available)
        try:
            self.backbone = models.googlenet(
                weights=models.GoogLeNet_Weights.IMAGENET1K_V1,
                aux_logits=False
            )
        except:
            print("Pretrained weights not available, using random init.")
            self.backbone = models.googlenet(weights=None, aux_logits=False)
        self.backbone.fc = nn.Identity()   # remove final layer -> 1024-dim features
        # Freeze backbone (train only LSTM + classifier)
        for param in self.backbone.parameters():
            param.requires_grad = False
        self.lstm = nn.LSTM(1024, hidden_size, num_layers, batch_first=True, dropout=0.5)
        self.classifier = nn.Linear(hidden_size, NUM_CLASSES)

    def forward(self, x):
        b, s, c, h, w = x.shape
        x = x.view(b * s, c, h, w)
        features = self.backbone(x)        # (b*s, 1024)
        features = features.view(b, s, -1) # (b, s, 1024)
        lstm_out, _ = self.lstm(features)
        return self.classifier(lstm_out[:, -1, :])

# ------------------------------
# 7. Training configuration
# ------------------------------
BATCH_SIZE = 8
EPOCHS = 20
LEARNING_RATE = 1e-4

def train_model(train_loader, val_loader, model, optimizer, criterion, epochs, device, save_path="best_model.pth"):
    best_acc = 0.0
    for epoch in range(epochs):
        model.train()
        train_correct, train_total = 0, 0
        for frames, labels in tqdm(train_loader, desc=f"Epoch {epoch+1} Training"):
            frames, labels = frames.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(frames)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            _, preds = torch.max(outputs, 1)
            train_total += labels.size(0)
            train_correct += (preds == labels).sum().item()

        model.eval()
        val_correct, val_total = 0, 0
        with torch.no_grad():
            for frames, labels in tqdm(val_loader, desc=f"Epoch {epoch+1} Validation"):
                frames, labels = frames.to(device), labels.to(device)
                outputs = model(frames)
                _, preds = torch.max(outputs, 1)
                val_total += labels.size(0)
                val_correct += (preds == labels).sum().item()

        train_acc = 100 * train_correct / train_total
        val_acc = 100 * val_correct / val_total
        print(f"Epoch {epoch+1}/{epochs} | Train Acc: {train_acc:.2f}% | Val Acc: {val_acc:.2f}%")

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), save_path)
            print(f"  -> Saved best model (val acc {val_acc:.2f}%)")
    print(f"Best validation accuracy: {best_acc:.2f}%")
    return model

# ------------------------------
# 8. Main execution
# ------------------------------
if __name__ == "__main__":
    dataset = BalancedVideoDataset(BASE_DIR, transform=transform)
    if len(dataset) == 0:
        raise RuntimeError("No videos found in balanced dataset.")

    labels = [dataset.samples[i][1] for i in range(len(dataset))]
    train_idx, val_idx = train_test_split(
        list(range(len(dataset))), test_size=0.2,
        stratify=labels, random_state=42
    )
    train_loader = DataLoader(Subset(dataset, train_idx), batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
    val_loader = DataLoader(Subset(dataset, val_idx), batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

    model = SceneClassifier().to(DEVICE)
    optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=LEARNING_RATE)
    criterion = nn.CrossEntropyLoss()

    model = train_model(train_loader, val_loader, model, optimizer, criterion, EPOCHS, DEVICE, save_path="scene_classifier.pth")

# =======================================================
# SINGLE CELL: Video Scene Understanding Engine
# - Downloads 4 datasets (or uses cached copies)
# - Balances classes to 123 videos per class
# - Trains GoogLeNet + LSTM on GPU
# =======================================================

# 1. Install dependencies
!pip install -q torch torchvision opencv-python scikit-learn tqdm kagglehub

# 2. Imports
import os
import glob
import random
import shutil
import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import kagglehub

# =======================================================
# 3. Dataset configuration
# =======================================================
DATASET_IDS = {
    "Sports": "abdallahwagih/ucf101-videos",
    "News": "reubensuju/celeb-df-v2",
    "Violence": "mohamedmustafa/real-life-violence-situations-dataset",
    "Movies": "pratt3000/moviesviolencenonviolence",
}
CLASS_NAMES = list(DATASET_IDS.keys())
BASE_DIR = "/content/balanced_dataset"
FRAMES_PER_VIDEO = 16
IMG_SIZE = 224
BATCH_SIZE = 8
EPOCHS = 20
LEARNING_RATE = 1e-4
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_CLASSES = 4

print(f"Using device: {DEVICE}")

# =======================================================
# 4. Download/retrieve dataset paths (uses cache)
# =======================================================
def get_dataset_path(dataset_id):
    print(f"Locating/Downloading {dataset_id} ...")
    path = kagglehub.dataset_download(dataset_id)
    print(f"  -> Path: {path}")
    return path

dataset_paths = {}
for cls, ds_id in DATASET_IDS.items():
    dataset_paths[cls] = get_dataset_path(ds_id)

# =======================================================
# 5. Filter rules (Violence only from "Violence" folder,
#    Movies only from "NonViolence" folder)
# =======================================================
def should_keep_video(cls, file_path):
    if cls == "Violence":
        return "Violence" in file_path and "NonViolence" not in file_path
    if cls == "Movies":
        return "NonViolence" in file_path
    return True

# Collect all video paths per class
class_videos = {}
for cls in CLASS_NAMES:
    src_root = dataset_paths[cls]
    video_exts = ('*.mp4', '*.avi', '*.mov', '*.mkv', '*.webm')
    videos = []
    for ext in video_exts:
        for video_path in glob.glob(os.path.join(src_root, '**', ext), recursive=True):
            if should_keep_video(cls, video_path):
                videos.append(video_path)
    class_videos[cls] = videos
    print(f"{cls}: {len(videos)} videos found")

# Determine smallest class size (Movies is likely the smallest)
min_size = min(len(v) for v in class_videos.values())
print(f"\nBalancing: taking {min_size} videos from each class (total {min_size * len(CLASS_NAMES)} videos).")

# =======================================================
# 6. Copy balanced subset to unified folder
# =======================================================
for cls in CLASS_NAMES:
    os.makedirs(os.path.join(BASE_DIR, cls), exist_ok=True)

random.seed(42)
for cls, video_list in class_videos.items():
    if len(video_list) < min_size:
        print(f"Warning: {cls} has only {len(video_list)} videos, using all of them.")
        selected = video_list
    else:
        selected = random.sample(video_list, min_size)
    target_dir = os.path.join(BASE_DIR, cls)
    for src in selected:
        shutil.copy(src, target_dir)
    print(f"Copied {len(selected)} videos to {cls}")

# =======================================================
# 7. Dataset class (extract 16 frames per video)
# =======================================================
transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

class BalancedVideoDataset(Dataset):
    def __init__(self, root_dir, frames_per_video=FRAMES_PER_VIDEO, transform=None):
        self.root_dir = root_dir
        self.frames_per_video = frames_per_video
        self.transform = transform
        self.samples = []
        for class_name in CLASS_NAMES:
            class_path = os.path.join(root_dir, class_name)
            if not os.path.isdir(class_path):
                continue
            label = CLASS_NAMES.index(class_name)
            for ext in ('*.mp4', '*.avi', '*.mov', '*.mkv', '*.webm'):
                for video_path in glob.glob(os.path.join(class_path, ext)):
                    self.samples.append((video_path, label))
        print(f"Balanced dataset ready: {len(self.samples)} videos total.")

    def _extract_frames(self, video_path):
        cap = cv2.VideoCapture(video_path)
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total_frames == 0:
            cap.release()
            raise ValueError("No frames")
        indices = np.linspace(0, total_frames - 1, self.frames_per_video, dtype=int)
        frames = []
        for idx in indices:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()
            if not ret:
                frame = frames[-1] if frames else np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8)
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            if self.transform:
                frame = self.transform(frame)
            frames.append(frame)
        cap.release()
        return torch.stack(frames)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        video_path, label = self.samples[idx]
        try:
            frames = self._extract_frames(video_path)
        except Exception:
            frames = torch.randn(self.frames_per_video, 3, IMG_SIZE, IMG_SIZE)
        return frames, label

# =======================================================
# 8. Model: GoogLeNet (frozen) + LSTM
# =======================================================
class SceneClassifier(nn.Module):
    def __init__(self, hidden_size=256, num_layers=2):
        super().__init__()
        # Load GoogLeNet with pretrained weights (uses torchvision cache)
        try:
            self.backbone = models.googlenet(
                weights=models.GoogLeNet_Weights.IMAGENET1K_V1,
                aux_logits=False
            )
        except Exception as e:
            print(f"Pretrained weights not available: {e}. Using random init.")
            self.backbone = models.googlenet(weights=None, aux_logits=False)
        self.backbone.fc = nn.Identity()   # remove final layer → 1024-dim features
        # Freeze backbone
        for param in self.backbone.parameters():
            param.requires_grad = False
        self.lstm = nn.LSTM(1024, hidden_size, num_layers, batch_first=True, dropout=0.5)
        self.classifier = nn.Linear(hidden_size, NUM_CLASSES)

    def forward(self, x):
        b, s, c, h, w = x.shape
        x = x.view(b * s, c, h, w)
        features = self.backbone(x)
        features = features.view(b, s, -1)
        lstm_out, _ = self.lstm(features)
        return self.classifier(lstm_out[:, -1, :])

# =======================================================
# 9. Training function
# =======================================================
def train_model(train_loader, val_loader, model, optimizer, criterion, epochs, device, save_path="best_model.pth"):
    best_acc = 0.0
    for epoch in range(epochs):
        model.train()
        train_correct, train_total = 0, 0
        loop = tqdm(train_loader, desc=f"Epoch {epoch+1} Training")
        for frames, labels in loop:
            frames, labels = frames.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(frames)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            _, preds = torch.max(outputs, 1)
            train_total += labels.size(0)
            train_correct += (preds == labels).sum().item()
            loop.set_postfix(loss=loss.item())

        model.eval()
        val_correct, val_total = 0, 0
        with torch.no_grad():
            for frames, labels in tqdm(val_loader, desc=f"Epoch {epoch+1} Validation"):
                frames, labels = frames.to(device), labels.to(device)
                outputs = model(frames)
                _, preds = torch.max(outputs, 1)
                val_total += labels.size(0)
                val_correct += (preds == labels).sum().item()

        train_acc = 100 * train_correct / train_total
        val_acc = 100 * val_correct / val_total
        print(f"Epoch {epoch+1}/{epochs} | Train Acc: {train_acc:.2f}% | Val Acc: {val_acc:.2f}%")

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), save_path)
            print(f"  -> Saved best model (val acc {val_acc:.2f}%)")
    print(f"Best validation accuracy: {best_acc:.2f}%")
    return model

# =======================================================
# 10. Main execution
# =======================================================
if __name__ == "__main__":
    # Load balanced dataset
    dataset = BalancedVideoDataset(BASE_DIR, transform=transform)
    if len(dataset) == 0:
        raise RuntimeError("No videos found after balancing. Check dataset downloads and filters.")

    # Train/val split (stratified)
    labels = [dataset.samples[i][1] for i in range(len(dataset))]
    train_idx, val_idx = train_test_split(
        list(range(len(dataset))), test_size=0.2,
        stratify=labels, random_state=42
    )
    train_loader = DataLoader(Subset(dataset, train_idx), batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
    val_loader = DataLoader(Subset(dataset, val_idx), batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

    # Model, optimizer, loss
    model = SceneClassifier().to(DEVICE)
    optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=LEARNING_RATE)
    criterion = nn.CrossEntropyLoss()

    # Train
    model = train_model(train_loader, val_loader, model, optimizer, criterion, EPOCHS, DEVICE, save_path="scene_classifier.pth")

print("\n🎉 Training complete! Best model saved as 'scene_classifier.pth'")

!rm -rf /content/checkpoints   # removes old checkpoints

!pip install -q torch torchvision opencv-python scikit-learn tqdm kagglehub seaborn matplotlib

import os, glob, random, shutil, numpy as np, cv2
import torch, torch.nn as nn, torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import kagglehub

DATASET_IDS = {
    "Sports": "abdallahwagih/ucf101-videos",
    "News": "reubensuju/celeb-df-v2",
    "Violence": "mohamedmustafa/real-life-violence-situations-dataset",
    "Movies": "pratt3000/moviesviolencenonviolence",
}
CLASS_NAMES = list(DATASET_IDS.keys())
BASE_DIR = "/content/balanced_dataset"
FRAMES_PER_VIDEO = 16
IMG_SIZE = 224
BATCH_SIZE = 8
EPOCHS = 20
LR_INIT = 1e-4
LR_FINE = 1e-5
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_CLASSES = 4
CHECKPOINT_DIR = "/content/checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

print(f"Using device: {DEVICE}")

def get_dataset_path(ds_id):
    print(f"Locating/Downloading {ds_id} ...")
    return kagglehub.dataset_download(ds_id)

dataset_paths = {cls: get_dataset_path(ds_id) for cls, ds_id in DATASET_IDS.items()}


def should_keep_video(cls, path):
    if cls == "Violence":
        return "Violence" in path and "NonViolence" not in path
    if cls == "Movies":
        return "NonViolence" in path
    return True

# Collect videos (only once)
if not os.path.exists(BASE_DIR) or len(os.listdir(BASE_DIR)) == 0:
    class_videos = {}
    for cls in CLASS_NAMES:
        src = dataset_paths[cls]
        videos = []
        for ext in ('*.mp4','*.avi','*.mov','*.mkv','*.webm'):
            for v in glob.glob(os.path.join(src, '**', ext), recursive=True):
                if should_keep_video(cls, v):
                    videos.append(v)
        class_videos[cls] = videos
        print(f"{cls}: {len(videos)} videos")

    min_size = min(len(v) for v in class_videos.values())
    print(f"\nBalancing: {min_size} videos per class → total {min_size*len(CLASS_NAMES)}")

    for cls in CLASS_NAMES:
        os.makedirs(os.path.join(BASE_DIR, cls), exist_ok=True)
    random.seed(42)
    for cls, vlist in class_videos.items():
        selected = random.sample(vlist, min_size) if len(vlist) >= min_size else vlist
        for src in selected:
            shutil.copy(src, os.path.join(BASE_DIR, cls, os.path.basename(src)))
        print(f"Copied {len(selected)} to {cls}")
else:
    print("Balanced dataset already exists. Skipping copy.")

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])
])

class BalancedVideoDataset(Dataset):
    def __init__(self, root_dir, frames=FRAMES_PER_VIDEO, transform=None):
        self.root_dir = root_dir
        self.frames = frames
        self.transform = transform
        self.samples = []
        for i, cls in enumerate(CLASS_NAMES):
            path = os.path.join(root_dir, cls)
            if not os.path.isdir(path):
                continue
            for ext in ('*.mp4','*.avi','*.mov','*.mkv','*.webm'):
                for v in glob.glob(os.path.join(path, ext)):
                    self.samples.append((v, i))
        print(f"Dataset: {len(self.samples)} videos")

    def _extract_frames(self, video_path):
        cap = cv2.VideoCapture(video_path)
        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        if total == 0:
            cap.release()
            raise ValueError("No frames")
        idxs = np.linspace(0, total-1, self.frames, dtype=int)
        frames = []
        for idx in idxs:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ret, frame = cap.read()
            if not ret:
                frame = frames[-1] if frames else np.zeros((IMG_SIZE,IMG_SIZE,3), dtype=np.uint8)
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            if self.transform:
                frame = self.transform(frame)
            frames.append(frame)
        cap.release()
        return torch.stack(frames)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label = self.samples[idx]
        try:
            frames = self._extract_frames(path)
        except:
            frames = torch.randn(self.frames, 3, IMG_SIZE, IMG_SIZE)
        return frames, label


class SceneClassifier(nn.Module):
    def __init__(self, hidden_size=256, num_layers=2):
        super().__init__()
        # Correctly load pretrained GoogLeNet with aux_logits=True
        self.backbone = models.googlenet(
            weights=models.GoogLeNet_Weights.IMAGENET1K_V1,
            aux_logits=True
        )
        self.backbone.fc = nn.Identity()   # remove final layer → 1024-dim
        for param in self.backbone.parameters():
            param.requires_grad = False
        self.lstm = nn.LSTM(1024, hidden_size, num_layers, batch_first=True, dropout=0.5)
        self.classifier = nn.Linear(hidden_size, NUM_CLASSES)

    def forward(self, x):
        b, s, c, h, w = x.shape
        x = x.view(b*s, c, h, w)
        features = self.backbone(x)[0]   # only main output
        features = features.view(b, s, -1)
        lstm_out, _ = self.lstm(features)
        return self.classifier(lstm_out[:, -1, :])


def load_checkpoint(model, optimizer, checkpoint_dir):
    checkpoint_files = [f for f in os.listdir(checkpoint_dir) if f.startswith("checkpoint_epoch_") and f.endswith(".pth")]
    if not checkpoint_files:
        return 0, None
    epochs = [int(f.split("_")[2].split(".")[0]) for f in checkpoint_files]
    latest_epoch = max(epochs)
    checkpoint_path = os.path.join(checkpoint_dir, f"checkpoint_epoch_{latest_epoch}.pth")
    checkpoint = torch.load(checkpoint_path, map_location=DEVICE)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    print(f"Resumed from checkpoint at epoch {latest_epoch}")
    return latest_epoch, checkpoint.get('best_acc', 0.0)

def save_checkpoint(model, optimizer, epoch, best_acc, checkpoint_dir):
    path = os.path.join(checkpoint_dir, f"checkpoint_epoch_{epoch}.pth")
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'best_acc': best_acc,
    }, path)
    # Keep only last 5 checkpoints
    all_chk = sorted([f for f in os.listdir(checkpoint_dir) if f.startswith("checkpoint_epoch_")])
    for old in all_chk[:-5]:
        os.remove(os.path.join(checkpoint_dir, old))

def train_model(train_loader, val_loader, model, optimizer, criterion, start_epoch, total_epochs, device, checkpoint_dir, save_path="best_model.pth"):
    best_acc = 0.0
    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

    # Load checkpoint if exists
    start_epoch, best_acc = load_checkpoint(model, optimizer, checkpoint_dir)
    if start_epoch >= total_epochs:
        print("Training already completed.")
        return model, history

    for epoch in range(start_epoch + 1, total_epochs + 1):
        # --- Training ---
        model.train()
        train_running_loss = 0.0
        train_correct, train_total = 0, 0
        loop = tqdm(train_loader, desc=f"Epoch {epoch} [Train]")
        for frames, labels in loop:
            frames, labels = frames.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(frames)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            train_running_loss += loss.item() * frames.size(0)
            _, preds = torch.max(outputs, 1)
            train_total += labels.size(0)
            train_correct += (preds == labels).sum().item()
            loop.set_postfix(loss=loss.item())

        epoch_train_loss = train_running_loss / train_total
        epoch_train_acc = 100 * train_correct / train_total


        model.eval()
        val_running_loss = 0.0
        val_correct, val_total = 0, 0
        with torch.no_grad():
            for frames, labels in tqdm(val_loader, desc=f"Epoch {epoch} [Val]"):
                frames, labels = frames.to(device), labels.to(device)
                outputs = model(frames)
                loss = criterion(outputs, labels)
                val_running_loss += loss.item() * frames.size(0)
                _, preds = torch.max(outputs, 1)
                val_total += labels.size(0)
                val_correct += (preds == labels).sum().item()

        epoch_val_loss = val_running_loss / val_total
        epoch_val_acc = 100 * val_correct / val_total


        history['train_loss'].append(epoch_train_loss)
        history['train_acc'].append(epoch_train_acc)
        history['val_loss'].append(epoch_val_loss)
        history['val_acc'].append(epoch_val_acc)

        print(f"Epoch {epoch}/{total_epochs} | Train Loss: {epoch_train_loss:.4f}, Acc: {epoch_train_acc:.2f}% | Val Loss: {epoch_val_loss:.4f}, Acc: {epoch_val_acc:.2f}%")

        if epoch_val_acc > best_acc:
            best_acc = epoch_val_acc
            torch.save(model.state_dict(), save_path)
            print(f"  *** model saved (val acc {best_acc:.2f}%) ***")

        save_checkpoint(model, optimizer, epoch, best_acc, checkpoint_dir)

    print(f"\nTraining completed. Best validation accuracy: {best_acc:.2f}%")
    return model, history

def plot_training_history(history):
    epochs = range(1, len(history['train_loss']) + 1)
    plt.figure(figsize=(14, 5))

    plt.subplot(1, 2, 1)
    plt.plot(epochs, history['train_loss'], 'o-', label='Train Loss')
    plt.plot(epochs, history['val_loss'], 'o-', label='Val Loss')
    plt.title('Loss per Epoch')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(epochs, history['train_acc'], 's-', label='Train Acc')
    plt.plot(epochs, history['val_acc'], 's-', label='Val Acc')
    plt.title('Accuracy per Epoch')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy (%)')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

def plot_confusion_matrix(model, val_loader, device, class_names):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for frames, labels in tqdm(val_loader, desc="Computing confusion matrix"):
            frames, labels = frames.to(device), labels.to(device)
            outputs = model(frames)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.title('Confusion Matrix')
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.show()

    # Also print classification report
    print("\nClassification Report:")
    print(classification_report(all_labels, all_preds, target_names=class_names))


if __name__ == "__main__":
    dataset = BalancedVideoDataset(BASE_DIR, transform=transform)
    if len(dataset) == 0:
        raise RuntimeError("No videos found.")

    labels = [dataset.samples[i][1] for i in range(len(dataset))]
    train_idx, val_idx = train_test_split(range(len(dataset)), test_size=0.2,
                                          stratify=labels, random_state=42)
    train_loader = DataLoader(Subset(dataset, train_idx), batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
    val_loader = DataLoader(Subset(dataset, val_idx), batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

    model = SceneClassifier().to(DEVICE)
    optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=LR_INIT)
    criterion = nn.CrossEntropyLoss()

    # Phase 1: Train only LSTM + classifier (backbone frozen)
    print("\n=== PHASE 1: Training LSTM + classifier (backbone frozen) ===")
    # We train up to 5 epochs, but checkpointing will resume automatically
    model, history1 = train_model(train_loader, val_loader, model, optimizer, criterion,
                                  start_epoch=0, total_epochs=5, device=DEVICE,
                                  checkpoint_dir=CHECKPOINT_DIR, save_path="phase1_best.pth")

    # Phase 2: Unfreeze last two Inception blocks of GoogLeNet
    print("\n=== PHASE 2: Fine‑tuning GoogLeNet (last two blocks) ===")
    for name, param in model.backbone.named_parameters():
        if 'mixed_6' in name or 'mixed_7' in name:
            param.requires_grad = True
    optimizer2 = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=LR_FINE)
    model, history2 = train_model(train_loader, val_loader, model, optimizer2, criterion,
                                  start_epoch=5, total_epochs=EPOCHS, device=DEVICE,
                                  checkpoint_dir=CHECKPOINT_DIR, save_path="scene_classifier.pth")

    # Merge histories for plotting (phase1 + phase2)
    full_history = {
        'train_loss': history1['train_loss'] + history2['train_loss'],
        'train_acc': history1['train_acc'] + history2['train_acc'],
        'val_loss': history1['val_loss'] + history2['val_loss'],
        'val_acc': history1['val_acc'] + history2['val_acc'],
    }

    # Plot training curves
    plot_training_history(full_history)

    # Confusion matrix on final validation set
    plot_confusion_matrix(model, val_loader, DEVICE, CLASS_NAMES)

    print("\n🎉 All done! Best model saved as 'scene_classifier.pth'.")